apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: pvc-snap
  namespace: experiment
spec:
  volumeSnapshotClassName: csi-snapclass
  source:
    persistentVolumeClaimName: datalake-dst