kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: datalake-dst
  namespace: rawdata
  annotations:
    trident.netapp.io/shareToNamespace: training
spec:
  accessModes:
    - ReadOnlyMany
  storageClassName: ontap-flexvol