---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: datalake-dst
  namespace: training
  annotations:
    trident.netapp.io/shareFromPVC: rawdata/datalake-dst
spec:
  accessModes:
    - ReadOnlyMany
  storageClassName: ontap-flexvol
  resources:
    requests:
      storage: 100Gi # specify same (or bigger) size as shared volume
---
apiVersion: trident.netapp.io/v1
kind: TridentVolumeReference
metadata:
  name: tvr-from-rawdata
  namespace: training
spec:
  pvcName: datalake-dst
  pvcNamespace: rawdata