apiVersion: v1
kind: Pod
metadata:
  name: inference-api
  labels:
    app: inference
spec:
  containers:
  - name: fastapi
    image: kyonsy0722/my-fastapi:0.6-beta
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: inference-api-service
spec:
  selector:
    app: inference
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: inference-api
spec:
  ingressClassName: "nginx"
  rules:
  - host: inference-api.ps-lab3.local
    http:
      paths:
      - pathType: ImplementationSpecific
        backend:
          service:
            name: inference-api-service
            port:
              number: 80