apiVersion: v1
kind: Pod
metadata:
  name: fastapi
  labels:
    app: fastapi
spec:
  containers:
  - name: fastapi
    image: kyonsy0722/my-fastapi:0.4-beta
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
spec:
  selector:
    app: fastapi
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fastapi
spec:
  ingressClassName: "nginx"
  rules:
  - host: fastapi.ps-lab3.local
    http:
      paths:
      - pathType: ImplementationSpecific
        backend:
          service:
            name: fastapi-service
            port:
              number: 80