name: ChatOps for MLOps
on: [issue_comment]

jobs:
  - label-pr:
      runs-on: ubuntu-latest
      steps:
        - name: listen for PR Comments (test)
          uses: machine-learning-apps/actions-chatops@master
          with:
            APP_PEM: ${{ secrets.APP_PEM }}
            APP_ID: ${{ secrets.APP_ID }}
            TRIGGER_PHRASE: "/test-trigger-comment"
            INDICATOR_LABEL: "test-label"
          env: # you must supply GITHUB_TOKEN
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          id: prcomm_test
        - name: listen for PR Comments (train model)
          uses: machine-learning-apps/actions-chatops@master
          with:
            APP_PEM: ${{ secrets.APP_PEM }}
            APP_ID: ${{ secrets.APP_ID }}
            TRIGGER_PHRASE: "/train-model"
            INDICATOR_LABEL: "train-model"
          env: # you must supply GITHUB_TOKEN
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          id: prcomm_train_model   
        - name: listen for PR Comments (serve model)
          uses: machine-learning-apps/actions-chatops@master
          with:
            APP_PEM: ${{ secrets.APP_PEM }}
            APP_ID: ${{ secrets.APP_ID }}
            TRIGGER_PHRASE: "/serve-model"
            INDICATOR_LABEL: "serve-model"
          env: # you must supply GITHUB_TOKEN
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          id: prcomm_serve_model
  - test:
      runs-on: self-hosted
      if: steps.prcomm_test.outputs.BOOL_TRIGGERED == 'true'
        # This step clones the branch of the PR associated with the triggering phrase, but only if it is triggered.
        - name: clone branch of PR
          uses: actions/checkout@master
          with:
            ref: ${{ steps.prcomm_test.outputs.SHA }}
          # This step is a toy example that illustrates how you can use outputs from the pr-command action
        - name: print variables
          run: echo "${USERNAME} made a triggering comment on PR# ${PR_NUMBER} for ${BRANCH_NAME}"
          env: 
            BRANCH_NAME: ${{ steps.prcomm_test.outputs.BRANCH_NAME }}
            PR_NUMBER: ${{ steps.prcomm_test.outputs.PULL_REQUEST_NUMBER }}
            USERNAME: ${{ steps.prcomm_test.outputs.COMMENTER_USERNAME }}
  - train:
      runs-on: self-hosted
      if: steps.prcomm_train_model.outputs.BOOL_TRIGGERED == 'true'
        # This step clones the branch of the PR associated with the triggering phrase, but only if it is triggered.
        - name: clone branch of PR
          uses: actions/checkout@master
          with:
            ref: ${{ steps.prcomm_train_model.outputs.SHA }}
        - name: compile, train and run pipeline
          run: echo "train model"
        - run : ls -l
  - serve:
      runs-on: self-hosted
      if: steps.prcomm_serve_model.outputs.BOOL_TRIGGERED == 'true'
        # This step clones the branch of the PR associated with the triggering phrase, but only if it is triggered.
        - name: clone branch of PR
          uses: actions/checkout@master
          with:
            ref: ${{ steps.prcomm_serve_model.outputs.SHA }}
        - name: compile, train and run pipeline
          run: echo "serve model"
        - run : ls -l