name: ChatOps for serving AI/ML model
on: [issue_comment]

jobs:
  detect_pr_comments:
    runs-on: self-hosted
    outputs: 
      model_uri: ${{ steps.output_model_uri.outputs.model_uri }}
      commit_sha: ${{ steps.output_sha.outputs.sha }}
    steps:
      # using below actions
      # https://github.com/marketplace/actions/chatops-for-pull-requests
      - name: listen for PR Comments (train)
        id: prcomm_serve
        uses: machine-learning-apps/actions-chatops@master
        with:
          APP_PEM: ${{ secrets.APP_PEM }}
          APP_ID: ${{ secrets.APP_ID }}
          TRIGGER_PHRASE: "/serve-model"
          INDICATOR_LABEL: "chatops-model-serving"
        env: # you must supply GITHUB_TOKEN
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # if PR comment does not match, abort this job
      - name: prcomm_check
        if: steps.prcomm_serve.outputs.BOOL_TRIGGERED == 'false'
        run: /bin/bash -c false
      # output variables for following jobs
      - id: create_outputs
        run: echo "model_uri=${{ steps.prcomm_serve.outputs.TRAILING_TOKEN }}" >> $GITHUB_OUTPUT
        run: echo "sha=${{ steps.prcomm_serve.outputs.SHA }}" >> $GITHUB_OUTPUT
  serving:
    runs-on: self-hosted
    needs: detect_pr_comments
    environment:
      name: Serving
    steps:
      # This step clones the branch of the PR associated with the triggering phrase, but only if it is triggered.
      - name: clone branch of PR
        uses: actions/checkout@master
        with:
          ref: ${{ steps.prcomm_serve.outputs.SHA }}
      - name: output repository name
        id: output_repository_name
        # from OWNER/REPOSITORY format, get only REPOSITORY name
        run: | 
          REPONAME=`echo ${{ github.repository }} | cut -f 2 -d "/" -`
          echo "repository_name=`echo $REPONAME | sed -e s/_/-/g`" >> $GITHUB_OUTPUT
      - name: deploy model by KServe
        run: python3 ./github_actions/deploy_model.py --namespace=${{ secrets.NAMESPACE }} --region=${{ secrets.ARTIFACT_REPO_REGION }} --access-key-base64=${{ secrets.ARTIFACT_REPO_ACCESS_KEY_BASE64 }} --secret-key-base64=${{ secrets.ARTIFACT_REPO_SECRET_KEY_BASE64 }} --model-name=${{ steps.output_repository_name.outputs.repository_name}} --model-uri=${{ needs.detect_pr_comments.outputs.model_uri }}
      - name: output virtual hostname
        id: output_virtual_hostname
        run: echo "virtual_hostname=`echo ${{ steps.output_repository_name.outputs.repository_name}}.${{ secrets.NAMESPACE }}.example.com`" >> $GITHUB_OUTPUT
      - name: test inference server
        id: test_inference_service
        run: python3 ./github_actions/test_inference_service.py --endpoint=${{ secrets.KUBEFLOW_ENDPOINT }} --username=${{ secrets.KUBEFLOW_USERNAME }} --password=${{ secrets.KUBEFLOW_PASSWORD }} --model-name=${{ steps.output_repository_name.outputs.repository_name}} --hostname=${{ steps.output_virtual_hostname.outputs.virtual_hostname}}
      # in case of passed the test
      - name: setup comment message (passed)
        if: ${{ steps.test_inference_service.result == 'success' }}
        id: success_comment
        run: |
          lf='\n'
          message="## :pushpin: Actions Result - Serving ML Model"
          message+="${lf}:rocket: ML model has been successfully served"
          echo "message=${message}" >> $GITHUB_OUTPUT
      - name: commenting on PR (passed) 
        if: ${{ needs.initiate-model-training-run.result == 'success' }}
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const params = {
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: '${{ steps.success_comment.outputs.message }}'
            }
            await github.rest.issues.createComment(params)
      # in case of failed
      - name: setup comment message (failure)
        if: ${{ needs.initiate-model-training-run.result == 'failure' }}
        id: failure_comment
        run: |
          lf='\n'
          message="## :pushpin: Actions Result - Serving ML Model"
          message+="${lf}:x: ML model has been deployed but failed to pass the test"
          echo "message=${message}" >> $GITHUB_OUTPUT
      - name: commenting on PR (failure) 
        if: ${{ needs.initiate-model-training-run.result == 'failure' }}
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const params = {
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: '${{ steps.failure_comment.outputs.message }}'
            }
            await github.rest.issues.createComment(params)